//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenXposure.Common
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XposureBase", Namespace="http://schemas.datacontract.org/2004/07/OpenXposure.Common")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OpenXposure.Common.XposureUser))]
    public partial class XposureBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ConnectionStringField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConnectionString
        {
            get
            {
                return this.ConnectionStringField;
            }
            set
            {
                this.ConnectionStringField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XposureUser", Namespace="http://schemas.datacontract.org/2004/07/OpenXposure.Common")]
    public partial class XposureUser : OpenXposure.Common.XposureBase
    {
        
        private int IdField;
        
        private string PasswordField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/OpenXposure.Common")]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal CurrentPriceField;
        
        private string DescriptionField;
        
        private System.DateTime EndTimeField;
        
        private string IdField;
        
        private bool IsEditField;
        
        private decimal StartPriceField;
        
        private System.DateTime StartTimeField;
        
        private string TitleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CurrentPrice
        {
            get
            {
                return this.CurrentPriceField;
            }
            set
            {
                this.CurrentPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime
        {
            get
            {
                return this.EndTimeField;
            }
            set
            {
                this.EndTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEdit
        {
            get
            {
                return this.IsEditField;
            }
            set
            {
                this.IsEditField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StartPrice
        {
            get
            {
                return this.StartPriceField;
            }
            set
            {
                this.StartPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDataService")]
public interface IDataService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ValidateUser", ReplyAction="http://tempuri.org/IDataService/ValidateUserResponse")]
    bool ValidateUser(OpenXposure.Common.XposureUser user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ValidateUser", ReplyAction="http://tempuri.org/IDataService/ValidateUserResponse")]
    System.Threading.Tasks.Task<bool> ValidateUserAsync(OpenXposure.Common.XposureUser user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetProduct", ReplyAction="http://tempuri.org/IDataService/GetProductResponse")]
    OpenXposure.Common.Product[] GetProduct(OpenXposure.Common.XposureUser user, string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetProduct", ReplyAction="http://tempuri.org/IDataService/GetProductResponse")]
    System.Threading.Tasks.Task<OpenXposure.Common.Product[]> GetProductAsync(OpenXposure.Common.XposureUser user, string id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDataServiceChannel : IDataService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DataServiceClient : System.ServiceModel.ClientBase<IDataService>, IDataService
{
    
    public DataServiceClient()
    {
    }
    
    public DataServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool ValidateUser(OpenXposure.Common.XposureUser user)
    {
        return base.Channel.ValidateUser(user);
    }
    
    public System.Threading.Tasks.Task<bool> ValidateUserAsync(OpenXposure.Common.XposureUser user)
    {
        return base.Channel.ValidateUserAsync(user);
    }
    
    public OpenXposure.Common.Product[] GetProduct(OpenXposure.Common.XposureUser user, string id)
    {
        return base.Channel.GetProduct(user, id);
    }
    
    public System.Threading.Tasks.Task<OpenXposure.Common.Product[]> GetProductAsync(OpenXposure.Common.XposureUser user, string id)
    {
        return base.Channel.GetProductAsync(user, id);
    }
}
